wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: catboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1661171687.762308
    t:
      1:
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 23
      4: 3.7.6
      5: 0.13.1
      8:
      - 5
